### ISSUE TITLE
Sap Flow development

### ISSUE THREAD

**Issue by mmaelicke** [KIT-HYD/bridget#23]
This is the missing stuff from #20:

General function layout for sap flow tools.
I provided the main functions in `sap_flow.py` and utility and correction functions in `util.py`. 

### ToDo

- [ ] add descriptions to all docstrings
- [x] check the parameters for data type and possible default values
- [ ] add data example, write unittests
- [x] implement the code

**Comment by mmaelicke** [comment]
Missing docstrings:

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L21

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L56

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L124

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L215

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L157

add a short sentence to:

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L144

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L151

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L174

https://github.com/KIT-HYD/bridget/blob/a78b53d435c8cd1d3b2b16570b4bd0aba545ea62/bridget/sap_flow/sap_flow.py#L192
